// motivationTalks.ts

const motivationQuotes = [
    "Believe in yourself and all that you are.",
    "Push yourself, because no one else is going to do it for you.",
    "Small changes make a big difference.",
    "Your only limit is your mind.",
    "Progress, not perfection.",
    "Don’t give up. Great things take time.",
    "Every step forward matters.",
    "Stay positive, work hard, make it happen.",
    "Success doesn’t come from what you do occasionally, it comes from what you do consistently.",
    "Doubt kills more dreams than failure ever will.",
    "Act as if what you do makes a difference. It does.",
    "Start where you are. Use what you have. Do what you can.",
    "Don’t watch the clock; do what it does. Keep going.",
    "The harder you work for something, the greater you’ll feel when you achieve it.",
    "Dream bigger. Do bigger.",
    "It’s going to be hard, but hard does not mean impossible.",
    "Don’t stop when you’re tired. Stop when you’re done.",
    "Wake up with determination. Go to bed with satisfaction.",
    "Little things make big days.",
    "It always seems impossible until it’s done.",
    "Push through the pain. You’re stronger than you think.",
    "Success is what comes after you stop making excuses.",
    "Believe you can and you’re halfway there.",
    "You don’t have to be great to start, but you have to start to be great.",
    "The key to success is to focus on goals, not obstacles.",
    "Difficult roads often lead to beautiful destinations.",
    "Work hard in silence. Let your success be your noise.",
    "Great things never come from comfort zones.",
    "Be proud of how far you’ve come.",
    "Start each day with a grateful heart.",
    "Hustle in silence and let your success make the noise.",
    "You’re closer than you were yesterday.",
    "Make today so awesome yesterday gets jealous.",
    "Turn your wounds into wisdom.",
    "Every accomplishment starts with the decision to try.",
    "Stay humble. Work hard. Be kind.",
    "If you’re going through hell, keep going.",
    "The only way to do great work is to love what you do.",
    "Push yourself to be your best self.",
    "Be stronger than your excuses.",
    "The future depends on what you do today.",
    "Focus on being productive instead of busy.",
    "Create a life you can’t wait to wake up to.",
    "Don’t let yesterday take up too much of today.",
    "Discipline is doing what needs to be done, even if you don’t want to do it.",
    "Train your mind to see the good in every situation.",
    "Success isn’t always about greatness. It’s about consistency.",
    "You were born to be real, not perfect.",
    "Do something today that your future self will thank you for.",
    "A little progress each day adds up to big results.",
    "Your goals don’t care how you feel.",
    "Stay focused and never give up.",
    "Keep your eyes on the stars and your feet on the ground.",
    "Focus on the step in front of you, not the whole staircase.",
    "Believe in your infinite potential.",
    "It’s never too late to be what you might have been.",
    "The best way out is always through.",
    "Success is not final, failure is not fatal: it is the courage to continue that counts.",
    "Start small. Think big.",
    "One day or day one. You decide.",
    "When you feel like quitting, think about why you started.",
    "Be the energy you want to attract.",
    "Strength doesn’t come from what you can do. It comes from overcoming the things you thought you couldn’t.",
    "Keep going. Everything you need will come to you.",
    "Every day is a second chance.",
    "You have to fight through some bad days to earn the best days.",
    "Keep your face always toward the sunshine—and shadows will fall behind you.",
    "Growth is growth, no matter how small.",
    "Don’t be afraid to start over. It’s a chance to build something better.",
    "If it doesn’t challenge you, it won’t change you.",
    "Don’t limit your challenges. Challenge your limits.",
    "Life is tough, but so are you.",
    "You are enough just as you are.",
    "Fall seven times, stand up eight.",
    "Consistency is more important than perfection.",
    "Take the risk or lose the chance.",
    "Every next level of your life will demand a different you.",
    "It’s not about having time. It’s about making time.",
    "You don’t get what you wish for. You get what you work for.",
    "Stay patient and trust your journey.",
    "The comeback is always stronger than the setback.",
    "Breathe. You’re going to make it.",
    "Work for it more than you hope for it.",
    "It’s okay to rest. Just don’t quit.",
    "Strive for progress, not perfection.",
    "There’s no elevator to success. You have to take the stairs.",
    "A winner is just a loser who tried one more time.",
    "Stay strong. The weekend is coming.",
    "Let your hustle be louder than your voice.",
    "One small positive thought can change your whole day.",
    "Today’s struggle is tomorrow’s strength.",
    "Think big. Trust yourself. Make it happen.",
    "Start with one step, just one.",
    "Stars can’t shine without darkness.",
    "Nothing worth having comes easy.",
    "Let your dreams be bigger than your fears.",
    "You are doing better than you think.",
    "Courage doesn’t always roar. Sometimes it’s the quiet voice at the end of the day saying, ‘I will try again tomorrow.’",
  ];
  
  export default motivationQuotes;
  